import Foundation

/// BMRCL's published timetable, generated by tools/build_timetable.py into
/// Resources/timetable.json. Terminal departures are BMRCL's; station-to-station
/// run and dwell times are modelled (BMRCL does not publish them).
struct Timetable: Decodable {
    struct Calendar: Decodable {
        /// ISO weekday ("1" = Monday) to service ID.
        let weekdays: [String: String]
        /// "yyyyMMdd" to service ID: 2nd/4th Saturdays and public holidays.
        let exceptions: [String: String]
    }

    struct Pattern: Decodable {
        struct Times: Decodable {
            /// Seconds from station i to the next station in this direction, by line-order index.
            let run: [Int]
            /// Seconds stood at station i when passing through.
            let dwell: [Int]
        }
        let stations: [String]
        let forward: Times
        let reverse: Times
    }

    struct Trip: Decodable {
        let service: String
        let lineID: String
        let direction: Direction
        /// Line-order station indices of the first and last stop.
        let from: Int
        let to: Int
        /// Departure from the first stop, seconds after the service day's midnight (may exceed 24 h).
        let start: Int

        init(from decoder: Decoder) throws {
            var c = try decoder.unkeyedContainer()
            service = try c.decode(String.self)
            lineID = try c.decode(String.self)
            direction = try c.decode(Direction.self)
            from = try c.decode(Int.self)
            to = try c.decode(Int.self)
            start = try c.decode(Int.self)
        }
    }

    let attribution: String
    let validUntil: String
    let calendar: Calendar
    let patterns: [String: Pattern]
    let trips: [Trip]
    /// Station ID to its name in Kannada script.
    let kannadaNames: [String: String]?

    static let bundled: Timetable = {
        guard let url = Bundle(for: TimetableBundleToken.self).url(forResource: "timetable", withExtension: "json"),
              let data = try? Data(contentsOf: url) else { fatalError("timetable.json missing from the app bundle") }
        do {
            return try JSONDecoder().decode(Timetable.self, from: data)
        } catch {
            fatalError("timetable.json: \(error)")
        }
    }()
}

private final class TimetableBundleToken {}
