import CoreLocation
import Foundation
import MapKit
import simd

/// Shared planar frame for the whole network: metres east (x) and south (y) of
/// Majestic, derived from Web Mercator so it lines up with MapKit imagery.
/// The 3D scene uses x as SceneKit x and y as SceneKit z.
enum MetroWorld {
    static let origin = CLLocationCoordinate2D(latitude: 12.9757, longitude: 77.5728)
    static let originPoint = MKMapPoint(origin)
    static let metersPerMapPoint = MKMetersPerMapPointAtLatitude(origin.latitude)

    static func project(_ c: CLLocationCoordinate2D) -> SIMD2<Double> {
        let p = MKMapPoint(c)
        return SIMD2((p.x - originPoint.x) * metersPerMapPoint, (p.y - originPoint.y) * metersPerMapPoint)
    }

    static func mapPoint(_ v: SIMD2<Double>) -> MKMapPoint {
        MKMapPoint(x: originPoint.x + v.x / metersPerMapPoint, y: originPoint.y + v.y / metersPerMapPoint)
    }
}

/// One line's alignment from OpenStreetMap (generated by tools/build_track.py),
/// resampled at a fixed spacing. Distances `s` are metres along the track from
/// the line's first station end, in the line's forward direction.
struct TrackGeometry {
    let lineID: String
    let points: [SIMD2<Double>]
    /// Deck-top height above ground: about 13 m on viaducts, negative in tunnels.
    let deck: [Double]
    let cumulative: [Double]
    let coordinates: [CLLocationCoordinate2D]
    let stationDistances: [Double]
    private let vertexTangents: [SIMD2<Double>]

    var length: Double { cumulative.last ?? 0 }

    init(lineID: String, coordinates: [CLLocationCoordinate2D], deck: [Double], stationIndices: [Int]) {
        precondition(coordinates.count >= 2 && coordinates.count == deck.count)
        self.lineID = lineID
        self.coordinates = coordinates
        self.deck = deck
        let points = coordinates.map(MetroWorld.project)
        self.points = points
        var cumulative = [0.0]
        for (a, b) in zip(points, points.dropFirst()) {
            cumulative.append(cumulative.last! + simd_distance(a, b))
        }
        self.cumulative = cumulative
        self.stationDistances = stationIndices.map { cumulative[$0] }
        self.vertexTangents = points.indices.map { i in
            let a = points[max(i - 1, 0)], b = points[min(i + 1, points.count - 1)]
            return simd_normalize(b - a)
        }
    }

    /// Segment index and fraction for a distance, clamped to the track.
    private func locate(_ s: Double) -> (Int, Double) {
        let s = min(max(s, 0), length)
        var lo = 0, hi = cumulative.count - 1
        while hi - lo > 1 {
            let mid = (lo + hi) / 2
            if cumulative[mid] <= s { lo = mid } else { hi = mid }
        }
        let span = cumulative[hi] - cumulative[lo]
        return (lo, span > 0 ? (s - cumulative[lo]) / span : 0)
    }

    func point(at s: Double) -> SIMD2<Double> {
        let (i, f) = locate(s)
        return points[i] + (points[i + 1] - points[i]) * f
    }

    func deckHeight(at s: Double) -> Double {
        let (i, f) = locate(s)
        return deck[i] + (deck[i + 1] - deck[i]) * f
    }

    /// Unit tangent in the forward direction, interpolated between vertices so it turns smoothly.
    func tangent(at s: Double) -> SIMD2<Double> {
        let (i, f) = locate(s)
        return simd_normalize(vertexTangents[i] + (vertexTangents[i + 1] - vertexTangents[i]) * f)
    }

    func coordinate(at s: Double) -> CLLocationCoordinate2D {
        let (i, f) = locate(s)
        let a = coordinates[i], b = coordinates[i + 1]
        return CLLocationCoordinate2D(
            latitude: a.latitude + (b.latitude - a.latitude) * f,
            longitude: a.longitude + (b.longitude - a.longitude) * f)
    }
}

/// Decodes NammaMetro/Resources/metro_track.json.
struct TrackFile: Decodable {
    struct Line: Decodable {
        struct Stop: Decodable {
            let osmName: String
            let trackIndex: Int
        }
        let id: String
        let lat: [Double]
        let lon: [Double]
        let deck: [Double]
        let stations: [Stop]
    }
    let attribution: String
    let lines: [Line]

    static func load() -> TrackFile {
        guard let url = Bundle(for: BundleToken.self).url(forResource: "metro_track", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let file = try? JSONDecoder().decode(TrackFile.self, from: data)
        else { fatalError("metro_track.json missing from the app bundle") }
        return file
    }
}

private final class BundleToken {}
