import CoreLocation
import SceneKit
import simd

/// OSM building footprints along the lines (Resources/buildings.bin, generated by
/// tools/build_buildings.py), grouped by the track chunk they stream in with.
struct CityBuilding {
    /// Footprint in `MetroWorld` metres (x east, y south).
    let footprint: [SIMD2<Double>]
    let height: Float
    let palette: Int
}

enum CityBuildings {
    /// Keyed "<lineID>-<chunk>".
    static let byChunk: [String: [CityBuilding]] = load()

    private static func load() -> [String: [CityBuilding]] {
        guard let url = Bundle.main.url(forResource: "buildings", withExtension: "bin"),
              let data = try? Data(contentsOf: url), data.count > 8,
              data.prefix(4) == Data("NMB1".utf8) else { return [:] }
        let lineIDs = MetroNetwork.lines.map(\.id)
        var out: [String: [CityBuilding]] = [:]
        data.withUnsafeBytes { raw in
            var o = 4
            func u8() -> Int { defer { o += 1 }; return Int(raw[o]) }
            func u16() -> Int { defer { o += 2 }; return Int(raw.loadUnaligned(fromByteOffset: o, as: UInt16.self).littleEndian) }
            func u32() -> Int { defer { o += 4 }; return Int(raw.loadUnaligned(fromByteOffset: o, as: UInt32.self).littleEndian) }
            func i32() -> Int32 { defer { o += 4 }; return raw.loadUnaligned(fromByteOffset: o, as: Int32.self).littleEndian }
            let count = u32()
            for _ in 0..<count {
                guard o + 7 <= raw.count else { break }
                let line = u8(), chunk = u16(), height = u16(), palette = u8(), n = u8()
                guard o + n * 8 <= raw.count else { break }
                var ring: [SIMD2<Double>] = []
                ring.reserveCapacity(n)
                for _ in 0..<n {
                    let lat = Double(i32()) / 1e6, lon = Double(i32()) / 1e6
                    ring.append(MetroWorld.project(CLLocationCoordinate2D(latitude: lat, longitude: lon)))
                }
                guard line < lineIDs.count else { continue }
                out["\(lineIDs[line])-\(chunk)", default: []]
                    .append(CityBuilding(footprint: ring, height: Float(height) / 10, palette: palette))
            }
        }
        return out
    }

    /// Extrudes buildings into one mesh: facade walls (6 palettes), flat roofs, and
    /// the black water tanks that sit on most Bengaluru roofs.
    static func node(for buildings: [CityBuilding], origin: SIMD2<Double>, materials: MetroMaterials) -> SCNNode? {
        let roofSlot = 6, tankSlot = 7
        var mesh = MeshBuilder(slots: 8)
        for b in buildings {
            var pts = b.footprint.map { SIMD2<Float>(Float($0.x - origin.x), Float($0.y - origin.y)) }
            if signedArea(pts) < 0 { pts.reverse() }
            let h = b.height
            let n = pts.count
            var run: Float = 0
            for i in 0..<n {
                let a = pts[i], c = pts[(i + 1) % n]
                let d = c - a
                let len = simd_length(d)
                guard len > 0.05 else { continue }
                // Positive area in (x, z): outward is (dz, -dx).
                let normal = simd_normalize(SIMD3<Float>(d.y, 0, -d.x))
                let u0 = run / 4, u1 = (run + len) / 4
                mesh.quad(b.palette, [[a.x, 0, a.y], [c.x, 0, c.y], [c.x, h, c.y], [a.x, h, a.y]], normal: normal,
                          uv: [[u0, 0], [u1, 0], [u1, h / FacadeSpec.floor], [u0, h / FacadeSpec.floor]])
                run += len
            }
            mesh.polygon(roofSlot, points: pts.map { [$0.x, h, $0.y] }, triangles: triangulate(pts), normal: [0, 1, 0])

            let area = abs(signedArea(pts))
            let pick = (Int(abs(b.footprint[0].x * 7.3 + b.footprint[0].y * 3.1)) % 10)
            if area > 60, pick < 6 {
                let cx = pts.reduce(SIMD2<Float>(0, 0), +) / Float(n)
                if pointInPolygon(cx, pts) {
                    mesh.cylinder(tankSlot, center: [cx.x, h + 0.6, cx.y], axis: [0, 1, 0], radius: 0.65,
                                  halfLength: 0.6, segments: 14)
                }
            }
        }
        let mats = materials.facades + [materials.buildingRoof, materials.waterTank]
        guard let g = mesh.geometry(materials: mats) else { return nil }
        let node = SCNNode(geometry: g)
        node.name = "buildings"
        node.castsShadow = true
        return node
    }

    static func signedArea(_ p: [SIMD2<Float>]) -> Float {
        var a: Float = 0
        for i in p.indices {
            let u = p[i], v = p[(i + 1) % p.count]
            a += u.x * v.y - v.x * u.y
        }
        return a / 2
    }

    static func pointInPolygon(_ q: SIMD2<Float>, _ p: [SIMD2<Float>]) -> Bool {
        var inside = false
        var j = p.count - 1
        for i in p.indices {
            if (p[i].y > q.y) != (p[j].y > q.y),
               q.x < (p[j].x - p[i].x) * (q.y - p[i].y) / (p[j].y - p[i].y) + p[i].x {
                inside.toggle()
            }
            j = i
        }
        return inside
    }

    /// Ear-clipping triangulation of a simple polygon with positive signed area.
    static func triangulate(_ p: [SIMD2<Float>]) -> [(Int, Int, Int)] {
        var idx = Array(p.indices)
        var tris: [(Int, Int, Int)] = []
        func cross(_ a: SIMD2<Float>, _ b: SIMD2<Float>) -> Float { a.x * b.y - a.y * b.x }
        func inTri(_ q: SIMD2<Float>, _ a: SIMD2<Float>, _ b: SIMD2<Float>, _ c: SIMD2<Float>) -> Bool {
            cross(b - a, q - a) >= 0 && cross(c - b, q - b) >= 0 && cross(a - c, q - c) >= 0
        }
        var guardCount = 0
        while idx.count > 3, guardCount < 400 {
            guardCount += 1
            var clipped = false
            for i in idx.indices {
                let a = idx[(i + idx.count - 1) % idx.count], b = idx[i], c = idx[(i + 1) % idx.count]
                guard cross(p[b] - p[a], p[c] - p[b]) > 0 else { continue }   // reflex corner
                if idx.contains(where: { $0 != a && $0 != b && $0 != c && inTri(p[$0], p[a], p[b], p[c]) }) { continue }
                tris.append((a, b, c))
                idx.remove(at: i)
                clipped = true
                break
            }
            if !clipped { break }
        }
        if idx.count == 3 {
            tris.append((idx[0], idx[1], idx[2]))
        } else if idx.count > 3 {
            for k in 1..<(idx.count - 1) { tris.append((idx[0], idx[k], idx[k + 1])) }   // degenerate fallback
        }
        return tris
    }
}

/// Facade texture layout: one texture tile spans 4 bays (4 m each) by 4 floors.
enum FacadeSpec {
    static let floor: Float = 3.2
    static let baysPerTile = 4
    static let floorsPerTile = 4
}
